### ISSUE TITLE
Error when Installing

### ISSUE THREAD

**Issue by futurealecks** [hughc/wordfence-slack-notifications#1]
Great idea! Tried to install this morning:

Parse error: syntax error, unexpected '[', expecting ')' in /home/XXX/public_html/wp-content/plugins/wordfence-slack-notifications-master/includes/class-wordfence-slack-notifications.php on line 194

**Comment by hughc** [comment]
Thanks for giving it a go!
I've removed a square bracket array constructor, to make the code compatible with PHP < 5.4.
